slim build \
    --target glua-dev:latest \
    --continue-after 15 \
    --show-clogs --show-blogs \
    --include-bin "/usr/bin/date" \
    --include-bin "/usr/bin/echo" \
    --include-bin "/usr/bin/cp" \
    --include-bin "/usr/bin/screen" \
    --include-shell \
    --expose 8080 \
    --tag glua-dev-slim:latest
